apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - name: client  # Added this
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: internal  # Added this
      protocol: TCP
      port: 9093
      targetPort: 9093
  type: ClusterIP
